# Generated by Django 5.0.3 on 2024-04-01 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_matricula_remove_discporcurso_curso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipovaliacao', models.CharField(max_length=100, verbose_name='Tipo de Avaliacao')),
            ],
            options={
                'verbose_name': 'TipoAvaliacao',
                'verbose_name_plural': 'TiposAvaliacoes',
            },
        ),
        migrations.CreateModel(
            name='DiscporCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carga_horaria', models.CharField(max_length=100, verbose_name='Carga Horaria')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.curso', verbose_name='Nome da Curso')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.disciplina', verbose_name='Nome da Disciplina')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.periodo', verbose_name='Periodo')),
            ],
            options={
                'verbose_name': 'DiscporCurso',
                'verbose_name_plural': 'DiscsporCursos',
            },
        ),
    ]
