# Generated by Django 5.0.3 on 2024-04-01 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_tipoavaliacao_discporcurso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipoavaliacao',
            old_name='tipovaliacao',
            new_name='tipoaval',
        ),
    ]
