# Generated by Django 5.0.3 on 2024-04-01 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_tipovaliacao_tipoavaliacao_tipoaval'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipoavaliacao',
            old_name='tipoaval',
            new_name='tipovaliacao',
        ),
    ]
