# Generated by Django 5.0.3 on 2024-04-01 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_disciplina_discporcurso_disc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discporcurso',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.curso', verbose_name='Nome do Curso'),
        ),
    ]
