# Generated by Django 5.0.3 on 2024-04-01 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_matricula_matricula'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipoavaliacao',
            old_name='tipovaliacao',
            new_name='tipoavaliacao',
        ),
    ]
